version: '2'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  api-server:
    build:
      context: ./server
    env_file:
      - ./.env
    ports:
      - '3001:80'
      - '443:443'
    volumes:
      - ./server:/app
    links:
      - redis
  client:
    build:
      context: ./client
    environment:
      - NODE_ENV=local
      - REACT_APP_API_SERVER_HOST=http://localhost:3001
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
